"""
Django settings for DSSCDB project.

Generated by 'django-admin startproject' using Django 1.9.7.

For more information on this file, see
https://docs.djangoproject.com/en/1.9/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/1.9/ref/settings/
"""

import os

from django.shortcuts import reverse

# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = '@&$!ob(=ba&#-jhflz89k#ms8e^n&(snei88zr#n(_8i67t*o='

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ['*']
context_processors = [
    'django.template.context_processors.media',
]

# Application definition
PAGINATION_NUMBER = 5

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'DSSCDB',  # Main project app
    'dye',  # App for chemistry data
    'usermanagement',  # Custom app for user management
    'sorl.thumbnail',  # Image thumbnails and caching
    'extended_choices',  # Better enumeration support for choices
    'bootstrap3',  # Neat forms
    'django.contrib.flatpages',  # Semi-dynamic pages such as "About"
    'django.contrib.sites',  # Easy domain management
    'post_office',  # Mail plugin
    'captcha',  # Re-captcha for "I'm not a robot" validation
]

MIDDLEWARE_CLASSES = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.auth.middleware.SessionAuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'DSSCDB.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'DSSCDB.wsgi.application'

# Database
# https://docs.djangoproject.com/en/1.9/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': os.path.join(BASE_DIR, 'db.sqlite3'),
    }
}

# Password validation
# https://docs.djangoproject.com/en/1.9/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]

# Internationalization
# https://docs.djangoproject.com/en/1.9/topics/i18n/

LANGUAGE_CODE = 'en-us'
TIME_ZONE = 'Europe/Oslo'
USE_I18N = True
USE_L10N = True
USE_TZ = True

# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/1.9/howto/static-files/

STATIC_URL = '/static/'
STATICFILES_DIRS = [
    #os.path.join(BASE_DIR, 'DSSCDB/'),
]


LOGIN_URL = '/user/login/'

# Parent directory of BASE_DIR
STATIC_ROOT = os.path.join(os.path.dirname(BASE_DIR), 'static')
MEDIA_ROOT = os.path.join(os.path.dirname(BASE_DIR), 'media')
MEDIA_URL = '/media/'
THUMBNAIL_DEBUG = True
THUMBNAIL_FORMAT = 'PNG'
THUMBNAIL_QUALITY = 100

EMAIL_USE_TLS = True
EMAIL_BACKEND = 'post_office.EmailBackend'
EMAIL_HOST = os.environ.get('EMAIL_HOST', '')
EMAIL_PORT = os.environ.get('EMAIL_PORT', '')
EMAIL_HOST_USER = os.environ.get('EMAIL_HOST_USER', '')
EMAIL_HOST_PASSWORD = os.environ.get('EMAIL_HOST_PASSWORD', '')
DEFAULT_FROM_MAIL = os.environ.get('EMAIL_DEFAULT_SENDER', '')
SERVER_EMAIL = DEFAULT_FROM_MAIL

ADMINS = [('Carl Johan Hambro', 'carljh@stud.ntnu.no'),]


LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'handlers': {
        'file': {
            'level': 'DEBUG',
            'class': 'logging.FileHandler',
            'filename': 'debug.log',
        },
        'image_file': {
            'level': 'DEBUG',
            'class': 'logging.FileHandler',
            'filename': 'image.log',
        },
        'mail_admins': {
            'level': 'ERROR',
            'class': 'django.utils.log.AdminEmailHandler'
        }
    },
    'loggers': {
        'image': {
            'handlers': ['image_file'],
            'level': 'DEBUG',
            'propagate': True,
        },
        'django': {
            'handlers': ['file'],
            'level': 'DEBUG',
            'propagate': True,
        },
        'django.request': {
            'handlers': ['mail_admins'],
            'level': 'ERROR',
            'propagate': True,
        },
    },
}

NOCAPTCHA = True
CAPTCHA_AJAX = True
CAPTCHA_WIDGET_TEMPLATE = 'captcha/widget_nocaptcha.html'

# Testing keys
RECAPTCHA_PUBLIC_KEY = '6LdrnzIUAAAAAGC_b1lJX6dLgpXj_G1GpFu3_G9I'
RECAPTCHA_PRIVATE_KEY = '6LdrnzIUAAAAAJD7kYs8fEn0CH_9NrFn8Jdi31Nt'

DATABASE_EMAIL_PASSWORD = os.environ.get('DATABASE_EMAIL_PASSWORD', '')
