# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-10-23 14:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dye', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='pages',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='article',
            name='volume',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterUniqueTogether(
            name='molecule',
            unique_together=set([('smiles', 'inchi')]),
        ),
    ]
