# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2018-02-12 10:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dye', '0004_add_sdf_to_molecules'),
    ]

    operations = [
        migrations.AlterField(
            model_name='molecule',
            name='image',
            field=models.FileField(blank=True, null=True, upload_to='molecules', verbose_name='Picture'),
        ),
    ]
