# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2018-02-14 18:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dye', '0005_auto_20180212_1133'),
    ]

    operations = [
        migrations.AddField(
            model_name='molecule',
            name='fingerprint',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
    ]
