# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-02-03 16:27
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import dye.models
import sorl.thumbnail.fields
import tinyuuidfield.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author', models.CharField(max_length=1000)),
                ('title', models.CharField(max_length=1000)),
                ('journal', models.CharField(max_length=250)),
                ('volume', models.CharField(max_length=100)),
                ('doi', models.CharField(max_length=500, unique=True, verbose_name='DOI')),
                ('pages', models.CharField(max_length=20)),
                ('issue_nr', models.CharField(blank=True, max_length=100, null=True)),
                ('eid', models.CharField(blank=True, max_length=100, null=True)),
                ('year', models.DateField()),
                ('electronic_id', models.CharField(max_length=250)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('keywords', models.CharField(blank=True, max_length=1000, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Contribution',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('short_id', models.CharField(default=dye.models.ShortID.generate_id, editable=False, max_length=8, unique=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('status', models.PositiveSmallIntegerField(choices=[(1, 'Waiting'), (2, 'Approved'), (3, 'Denied')], default=1)),
                ('articles', models.ManyToManyField(blank=True, null=True, to='dye.Article')),
            ],
            options={
                'permissions': (('upload_performance_data', 'Can upload performance data'), ('set_contribution_status', 'Can change status on contributions')),
            },
        ),
        migrations.CreateModel(
            name='Molecule',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('smiles', models.CharField(help_text='Example field help text.', max_length=1000, unique=True, verbose_name='SMILES')),
                ('inchi', models.CharField(max_length=1000, unique=True, verbose_name='INCHI')),
                ('image', sorl.thumbnail.fields.ImageField(blank=True, null=True, upload_to='molecules', verbose_name='Picture')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('keywords', models.CharField(blank=True, max_length=1000, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Performance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('voc', models.DecimalField(decimal_places=4, max_digits=15, verbose_name='VOC')),
                ('jsc', models.DecimalField(decimal_places=5, max_digits=15, verbose_name='JSC')),
                ('ff', models.DecimalField(decimal_places=5, max_digits=13, verbose_name='FF')),
                ('pce', models.DecimalField(decimal_places=5, max_digits=13, verbose_name='PCE')),
                ('electrolyte', models.CharField(max_length=1000)),
                ('active_area', models.CharField(help_text='cm2', max_length=30)),
                ('co_adsorbent', models.CharField(blank=True, max_length=250, null=True)),
                ('co_sensitizer', models.CharField(blank=True, max_length=1000, null=True)),
                ('semiconductor', models.CharField(max_length=1000)),
                ('dye_loading', models.CharField(help_text='nmol/cm2', max_length=1000)),
                ('exposure_time', models.CharField(max_length=500)),
                ('solar_simulator', models.CharField(max_length=1000)),
                ('keywords', models.CharField(blank=True, max_length=1000, null=True)),
                ('short_id', models.CharField(default=dye.models.ShortID.generate_id, editable=False, max_length=8, unique=True)),
                ('comment', models.TextField()),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('status', models.PositiveSmallIntegerField(choices=[(1, 'Waiting'), (2, 'Approved'), (3, 'Denied')], default=1)),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='performances', to='dye.Article')),
                ('molecule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='performances', to='dye.Molecule')),
            ],
            options={
                'verbose_name': 'DSSC performance',
            },
        ),
        migrations.CreateModel(
            name='ShortID',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(default=dye.models.get_unique_id, editable=False, max_length=8, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Spectrum',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('absorption_maxima', models.DecimalField(blank=True, decimal_places=4, help_text='[kg/s]', max_digits=10, null=True)),
                ('emission_maxima', models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True)),
                ('solvent', models.CharField(max_length=100)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('status', models.PositiveSmallIntegerField(choices=[(1, 'Waiting'), (2, 'Approved'), (3, 'Denied')], default=1)),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='spectra', to='dye.Article')),
                ('molecule', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='spectrum', to='dye.Molecule')),
            ],
            options={
                'verbose_name_plural': 'Molecule spectra',
                'verbose_name': 'Molecule spectrum',
            },
        ),
        migrations.CreateModel(
            name='Spreadsheet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='spreadsheets')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Test',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tiny_id', tinyuuidfield.fields.TinyUUIDField(blank=True, editable=False, max_length=10, unique=True)),
            ],
        ),
        migrations.AddField(
            model_name='contribution',
            name='molecules',
            field=models.ManyToManyField(to='dye.Molecule'),
        ),
        migrations.AddField(
            model_name='contribution',
            name='performances',
            field=models.ManyToManyField(blank=True, null=True, to='dye.Performance'),
        ),
        migrations.AddField(
            model_name='contribution',
            name='specta',
            field=models.ManyToManyField(blank=True, null=True, to='dye.Spectrum'),
        ),
        migrations.AddField(
            model_name='contribution',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contributions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterUniqueTogether(
            name='spectrum',
            unique_together=set([('molecule', 'article')]),
        ),
    ]
